### ISSUE TITLE
Divide the whole database into 4 mini-database

### ISSUE THREAD

**Issue by calpa** [manami-project/anime-offline-database#12]
Background: 
This database is awesome, but the `anime-offline-database.json` seems too large, 19.4 MB.

When I view the file, Github shows this:

![2019-02-01 10 35 28](https://user-images.githubusercontent.com/19569045/52099186-204f2980-260d-11e9-8d26-2e7688807755.jpg)

15444 entries from myanimelist.net
10472 entries from anidb.net
11270 entries from anilist.co
14201 entries from kitsu.io

Proposal:
Divide the whole database into 4 mini-database based on their source.

**Comment by Xetera** [comment]
It seems to me as though the point of the repo is to have everything in one place. A single json file makes it very easy to import the data in something like a search engine, as I've done here https://github.com/weebsearch/librarian So I would like to not see that change and have to fiddle around with combining multiple files.

I'm guessing that might also create problems with duplicates as well, so there's also that.

**Comment by manami-project** [comment]
Hey all,
it's cool to see you guy's being interested in the project.

@calpa I understand that you suggest to split the data by meta data providers in order to shrink the file size. However one benefit is that the database allows cross referencing anime between meta data providers. Then there are two options. Either this feature is lost by splitting it up into various files or a mechanism to create relations between the different entries throughout the files is needed. That means that a user needs to merge this back together again. Basically @Xetera summed that up pretty good already.

The question is: For which use case is the file size too large? If it's about the diff within github, I have to admit that I don't care about that. Parsing should not be a problem from my perspective.

**Comment by cc-jhr** [comment]
Hey @calpa,

haven't heard from you in a week. So I am closing this issue.
If there is still need for discussing this topic we can repoen this issue of course.

**Comment by manami-project** [comment]
Hey @calpa,

haven't heard from you in a week so I am closing this issue.
If there is still need for discussing this topic, we can repoen it of course.
