### ISSUE TITLE
Extra addition if possible: Synopsis and genres

### ISSUE THREAD

**Issue by ultrawazer** [manami-project/anime-offline-database#30]
Hey! Above all, thank you so much for the work here! You are awesome!
Is it possible to add synopsis and years to the list? 
Also is adding genres also possible? I know it might be too much work than its worth, but if it would be possible to add I would be forever grateful.
Once again, thanks for the awesome work.

**Comment by manami-project** [comment]
Hey @ultrawazer,
thank you for your interest in this project.

So first things first: This database was created for my own tool (as stated in the README.md). So if I don't need it there then I wouldn't add it. And here comes a detailed explanation to this:

Yes it's kind of a lot of work. Why? Data is difficult! I only use the minimum amount of information here to identify and describe an anime. The links to the sources are very important, because in my opinion that is the place where you get all your additional information. These communities  are constantly working on the anime data and debating which information is correct and/or should be added/removed/changed. So I never planned for this project to make one of these sites (or all of them) obsolete. Instead I want to provide some kind of table of contents which is useful for my project and might be a help for other projects or inspire people to create completely new projects.

Back to the topic "data". In this project I try to merge the data of different anime sites to a logical entry. But data varies on these sites. As I said I try to only use basic data. And here I mean data that is not subjective. However even this fair amount of data I present is difficult. It starts with one site listing an anime as `special` whereas the other lists it as `OVA`. Even episodes may differ. For example if one site lists 12 episodes and the other 13, because the special which is listed separately on the first site is included in the second. And that is just the data that one might think is not discussable. So **genres** would be the ultimate overkill I think. I could just merge them all together as is. But there might be the same genres across the sites slightly different written or expressed. Should those be unified or not? People arguing whether or not a specific genre is justified for an anime, although this is just aggregated data. You get the idea...

I am already extracting the **year** of premiere for the merging. Just the year of the premiere, not the exact start date and not the time span of airing. Have a look at the merge-preventions.md. It's full of entries which could be considered the same anime, but have different years(!) of premiere. Same challenge. I plan to add the status of airing (#27) Maybe this is helpful to you?

I will never add **synopsis**, because of legal reasons. Those _might_ be texts protected by copyright. I mean it's a creatively written text. A lawyer would have to give me a green light for this. But despite that: Should I really list 3-4 synopsis? This is something you cannot merge. Wouldn't this go against the whole idea of this database? Merged entries wouldn't make sense anymore., they should be separated. But then it's just a download of all the anime sites. That doesn't make sense to me.

I know it might sound frustrating to you that I reject all of your requests. But I hope I was able to explain why. Maybe this database is still helpful to you.
