### ISSUE TITLE
[Docs] Add a section on the readme to explain how the animes are match between sites

### ISSUE THREAD

**Issue by germancasares** [manami-project/anime-offline-database#32]
Hi,

I just found out about this project and, looks amazing and a hell lot of work. I am working on a personal project (To auto teach me Vue/.Net core) and until now I have been using Kitsu, but I would like to have  links to AniDB and MAL.

I was thinking of using this DB, but my only concern is how trusty is this process, so this section in the Readme will help me and other possible future developers that want to use this DB.

Again, great work doing this massive job.

**Comment by manami-project** [comment]
Hi @germancasares,

first of all thank you for your interest in this project.

> I am working on a personal project (To auto teach me Vue/.Net core) and until now I have been using Kitsu, but I would like to have links to AniDB and MAL.
> I was thinking of using this DB, but my only concern is how trusty is this process, so this section in the Readme will help me and other possible future developers that want to use this DB.

If you start with a new project whose main goal is to teach you new technologies (in your case vue and net.core) then I think that you might want to focus on those technologies first and less on other things like how this database is created in detail.  Anyway, I don't get the "how trusty is this process" part. What exactly is your concern here?
Of course it is not perfect. However in the [latest release](https://github.com/manami-project/anime-offline-database/issues/32) I mentioned how many entries have been verified. After checking so many entries I can still say that I'm content with the quality. I tried to make the merging defensive, so that two entries are rather not merged together than have been falsely merged.
I am not sure whether this helps to resolve your concerns or not. If you still have concerns, just try it out or maybe compare whatever you want to achieve with the results you gain using other data sources.

I won't add a documentation about the merging process in this repository, because it just doesn't belong here. It should be part of the tool which I use to create this database. That's where, in my opinion, that documentation belongs. This repository is just the artifact and its documentation should only document the content of the repository.

**Comment by Py-Monsters** [comment]
@manami-project 
> That's where, in my opinion, that documentation belongs. This repository is just the artifact and its documentation should only document the content of the repository.

Sorry for interrupting, I am trying to make a similar database to this one (only anilist, mal, kitsu) which uses their APIs to get all the information I need, but the process of merging them isn't as good and accurate as this database. So, what do you map anime based on? And where can I find the docs of the "tool" used to create this directory.

Thank you,
