### ISSUE TITLE
Can you update relation name ?

### ISSUE THREAD

**Issue by meotimdihia** [manami-project/anime-offline-database#44]
Relation names are 'sequel', 'prequel', 'adaption', ... 
I want to use relation for my website, but it's hard to use when I don't have what is relation name?

**Comment by manami-project** [comment]
Currently I don't plan to add that info.

**Comment by spillerrec** [comment]
I would like to request this as well as the relation types are carrying a lot of important information. I'm currently using this database to map anime titles to AniList ids, but I'm running into issues with some titles using season numbers, say `Gochuumon wa Usagi Desu ka? S3` instead of `Gochuumon wa Usagi Desu ka? BLOOM` (and sometimes both to be extra confusing).

Using the relations together with the anime type and release date I should be able to figure out the season number for those series were it is not disputed. Except that some of those relations are for spin-offs or remakes, take for example `Index` and `Railgun` where the spin-off has its own entire hierarchy.
It gets more crazy due to silly relations from ads/specials containing cameos/crossovers. Here is the relation graph for `Attack on Titan`:
![attack-on-titan](https://user-images.githubusercontent.com/2292170/100149285-3c852000-2e9e-11eb-88a7-85926b64dd62.png)
It ends up being connected to `Ghost in the Shell` through `Animegatari` which happened to do collabs with both of the franchises and therefore has `Character` relations.

I could possible do some of this season analysis through the synonyms, but there is a lot of garbage there as well and I would preferably like to do both. I'm not sure what the best way would be to retrofit this information, but it would greatly increase the usefulness of the relations.
Personally I would be fine with either having a raw dump of the crawled data so I can extract it myself or having it as a separate JSON file that gets updated yearly, the main reason I'm using this database is to avoid hitting their servers with thousands of requests.
