### ISSUE TITLE
I don't have an issue...just came here to thank you.....

### ISSUE THREAD

**Issue by August4599** [manami-project/anime-offline-database#49]
As mentioned in the title....thank you so much for making this 30000 is amazing.......just wanted to ask if watch order of anime will be added to the json.????

Thank you for your hard work

**Comment by manami-project** [comment]
Hi @August4599,
> As mentioned in the title....thank you so much for making this 30000 is amazing.......
> [...]
> Thank you for your hard work

That's nice to hear. I'm glad if it's useful for you as well.

> just wanted to ask if watch order of anime will be added to the json.????

Did you really just sneak in a question? :) As mentioned in the [FAQ](https://github.com/manami-project/anime-offline-database/blob/master/.github/CONTRIBUTING.md#can-you-please-add-additional-information) I don't have plans to add additional data at the moment.
However by "watch order of anime" I understand that you mean the order in which you're supposed to watch an anime with multiple publications. e.g.: season1, season2, movie, ova, season3 <- something like that?
That is actually an interesting case, because I see two possibilities. You can either use an order to watch based on the release dates or you could decide to watch the anime in its natural order. By natural order I mean that you would watch a prequel which has a more recent release date before its preceding sequel/original.
Anyway for both cases I'd recommend a different data set.
