### ISSUE TITLE
any plans for manga-offline-database

### ISSUE THREAD

**Issue by edgehub-cloud** [manami-project/anime-offline-database#57]
i Believe a lot of manga meta aggregators have harsh rate limits so a offline db would help a lot of application liike komga , kavita adding meta to files. there is comicvine too
sources = manga updates , comicvine (volume based meta data} , anilist , mal 
i know it was closed in past but are there any changes in plans for future*

**Comment by manami-project** [comment]
Hello @edgehub-cloud,

I still have no plans to create a similar data set for manga and I guess that this won't change in the foreseeable future.
One reason is that I don't have a project which needs it and therefore no necessity for it. This repo is actually just a side project originating from [manami](https://github.com/manami-project/manami). So without manami I wouldn't have created it.
The other reason is that despite the automation already in place I still invest a huge amount of time in order to keep this data set continuously updated. Which means that another project like this would be too time consuming. Especially if I don't need it for a project of my own.
