### ISSUE TITLE
Docs to explain how anime entries are merged between sites

### ISSUE THREAD

**Issue by Majticz** [manami-project/anime-offline-database#65]
First of all, I am deeply sorry for coming back to such an old issue.

https://github.com/manami-project/anime-offline-database/issues/32#issuecomment-605688351
> That's where, in my opinion, that documentation belongs. This repository is just the artifact and its documentation should only document the content of the repository.

Sorry for interrupting, I am trying to make a similar database to this one (only anilist, mal, kitsu) which uses their APIs to get all the information I need, but the process of merging them isn't as good and accurate as this database. So, what do you map anime based on? And where can I find the docs of the "tool" used to create this directory.

Thank you,

**Comment by manami-project** [comment]
> And where can I find the docs of the "tool" used to create this directory.

It hasn't been released yet. I just don't have the time.

> [...], but the process of merging them isn't as good and accurate as this database

As I wrote in in the comment that you linked. I used a very defensive merging strategy. Based on that: Don't underestimate the amound of manual overrides I create. As you can see in the README.md, I reviewed all entries in this data set. So whatever you do, you just can't compare it to this data set, because of the manual reviews.
